# Generated by Django 5.2.6 on 2025-09-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('lain-lain', 'Lain-Lain'), ('celana', 'Celana')], default='lain-lain'),
        ),
    ]
